services:
  services-auth:
    build:
      context: ../..
      dockerfile: ./services/auth/Dockerfile
    volumes:
      - ../../dbs/auth/data:/app/dbs/auth/data
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm start
    develop:
      watch:
        - action: sync+restart
          path: ../../dbs/auth/src
          target: /app/dbs/auth/src
        - action: sync+restart
          path: ../../dbs/auth/index.ts
          target: /app/dbs/auth/index.ts
        - action: sync+restart
          path: ../../dbs/auth/drizzle.config.ts
          target: /app/dbs/auth/drizzle.config.ts
        - action: sync+restart
          path: ../../dbs/auth/types
          target: /app/dbs/auth/types
        - action: sync+restart
          path: ../../dbs/auth/migrations
          target: /app/dbs/auth/migrations
        - action: sync+restart
          path: ../../dbs/auth/tsconfig.json
          target: /app/dbs/auth/tsconfig.json
        - action: sync+restart
          path: ../../specs/apis/dist
          target: /app/specs/apis/dist
        - action: sync+restart
          path: .
          target: /app/services/auth
