services:
  vue-app:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./vue-app:/app
      - /app/node_modules # So HMR works
    environment:
      - NODE_ENV=production # per nodejs.org, always run in prod
    command: npm run dev
    depends_on:
      - api-app

  api-app:
    build:
      context: ./
      dockerfile: ./api-app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./db/data:/app/db/data
    environment:
      - NODE_ENV=production
      - SQLITE_DB_PATH=/app/data/database.sqlite
      - PORT=3000
    command: npm start
    develop:
      watch:
        - action: sync+restart
          path: ./api-app/
          target: /app/api-app
          ignore:
            - ./api-app/node_modules/
        - action: sync+restart
          path: ./db
          target: /app/db
          ignore:
            - ./db/node_modules/
            - ./db/data/
        - action: rebuild
          path: ./api-app/package.json
          target: /app/api-app/package.json
        - action: rebuild
          path: ./db/package.json
          target: /app/db/package.json
# is this needed?
volumes:
  sqlite-data: