services:
  caddy:
    image: caddy:2.9.1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - clients
      - services__auth
      - services__api

  clients:
    build:
      context: ./
      dockerfile: ./clients/Dockerfile
    volumes:
      - ./clients:/app/clients
      - /app/clients/node_modules # So HMR works
    command: npm run dev

  services__auth:
    build:
      context: ./
      dockerfile: ./services/auth/Dockerfile
    volumes:
      - ./dbs/auth/data:/app/dbs/auth/data
    environment:
      - SQLITE_DB_PATH=/app/data/database.sqlite
      - PORT=3000
      - NODE_ENV=development
    command: npm start
    develop:
      watch:
        - action: sync+restart
          path: ./services/auth
          target: /app/services/auth
          ignore:
            - ./services/auth/node_modules/

        # ../db
        - action: sync+restart
          path: ./dbs/auth/src
          target: /app/dbs/auth/src

        # ../specs/apis
        - action: sync+restart
          path: ./specs/apis/dist
          target: /app/specs/apis/dist

  services__api:
    build:
      context: ./
      dockerfile: ./services/api/Dockerfile
    environment:
      - PORT=3002
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:80 # Updated to use Caddy's port
    command: npm start
    develop:
      watch:
        - action: sync+restart
          path: ./services/api
          target: /app/services/api
          ignore:
            - ./services/api/node_modules/

        # ../db
        - action: sync+restart
          path: ./dbs/main/src
          target: /app/dbs/main/src
          ignore:
            - ./dbs/main/node_modules/

        # ../specs/apis
        - action: sync+restart
          path: ./specs/apis/dist
          target: /app/specs/apis/dist

  specs__apis:
    build:
      context: ./
      dockerfile: ./specs/apis/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./specs/apis/dist:/app/specs/apis/dist
    develop:
      watch:
        - action: sync+restart
          path: ./specs/apis/openapi.yaml
          target: /app/specs/apis/openapi.yaml
    command: npm run generate-and-serve

volumes:
  caddy_data:
  caddy_config: