services:
  vue-app:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite's default port
    volumes:
      - ./vue-app:/app

      # Claude put Node modules in Docker volumes to
      # "prevent conflicts with local environment".
      - /app/node_modules
    environment:
      # per nodejs.org, always run in prod. Code that depends
      # on environment is an antipattern.
      - NODE_ENV=production
    command: npm run dev
    depends_on:
      - api-app

  api-app:
    build:
      context: ./
      dockerfile: ./api-app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/api-app/node_modules
      - ./api-app/data:/app/api-app/data
      - ./db:/app/db
    environment:
      - NODE_ENV=production
      - SQLITE_DB_PATH=/app/data/database.sqlite
      - PORT=3000
    command: npm start
    develop:
      watch:
        - action: sync+restart
          path: ./api-app/
          target: /app/api-app
          ignore:
            - ./api-app/node_modules/
            - ./api-app/data/
            - ./node_modules/

# is this needed?
volumes:
  sqlite-data: