openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: Example API specification for the template service

paths:
  /example:
    get:
      summary: Get all examples
      responses:
        "200":
          description: List of examples
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Example"
    post:
      summary: Create a new example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Created example
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Example"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /example/{id}:
    get:
      summary: Get example by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Example item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Example"
        "404":
          description: Example not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Example:
      type: object
      required:
        - id
        - name
        - createdAt
      properties:
        id:
          type: integer
        name:
          type: string
        createdAt:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        error:
          type: string
        details:
          type: array
          items:
            type: object
