services:
  caddy:
    cap_add:
      - NET_ADMIN
    image: ghcr.io/sderickson/saf-2025-caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DISABLE_VITE_DEV_SERVER=#
      - DOMAIN=${DOMAIN}
      - PROTOCOL=${PROTOCOL}
    volumes:
      - ./config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  api:
    image: ghcr.io/sderickson/saf-2025-api:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    memswap_limit: 2G
    volumes:
      - /opt/app/dbs/main/data:/app/dbs/main/data

  auth:
    image: ghcr.io/sderickson/saf-2025-auth:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    memswap_limit: 2G
    volumes:
      - /opt/saf-2025/saflib/auth-db/data:/app/saflib/auth-db/data
      - /opt/saf-2025/saflib/auth-service/data:/app/saflib/auth-service/data

volumes:
  caddy_data:
  caddy_config:
