services:
  caddy:
    cap_add:
      - NET_ADMIN
    image: ghcr.io/sderickson/saf-caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DISABLE_VITE_DEV_SERVER=#
      - DOMAIN=${DOMAIN}
      - PROTOCOL=${PROTOCOL}
    volumes:
      - ./config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    # TODO: Figure out how to build separately
    # build:
    #   context: ../..
    #   dockerfile: deploy/instance/Dockerfile.prod

  # services-api:
  #   image: ghcr.io/sderickson/saf-services-api:latest
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - PROTOCOL=${PROTOCOL}
  #   restart: unless-stopped

  services-auth:
    image: ghcr.io/sderickson/saf-services-auth:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - PROTOCOL=${PROTOCOL}
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: 