services:
  caddy:
    cap_add:
      - NET_ADMIN
    image: ghcr.io/sderickson/saf-caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DISABLE_VITE_DEV_SERVER=#
      - DOMAIN=${DOMAIN}
      - PROTOCOL=${PROTOCOL}
    volumes:
      - ./config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  services-api:
    image: ghcr.io/sderickson/saf-services-api:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    memswap_limit: 2G

  services-auth:
    image: ghcr.io/sderickson/saf-services-auth:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    memswap_limit: 2G

volumes:
  caddy_data:
  caddy_config: 