services:
  caddy:
    cap_add:
      - NET_ADMIN
    image: ghcr.io/sderickson/saf-2025-caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DISABLE_VITE_DEV_SERVER=#
      - DOMAIN=${DOMAIN}
      - PROTOCOL=${PROTOCOL}
    volumes:
      - ./config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
