# syntax=docker/dockerfile:labs
FROM node:22-slim AS builder

WORKDIR /app
#{ copy_packages }#
RUN npm install --omit=dev
#{ copy_src }#

# Make the documentation accessible to vitepress
COPY ./saflib ./saflib

# # Vue app setup
WORKDIR /app/clients/docs