services:
  caddy:
    image: caddy:2.9.1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}

  clients:
    build:
      context: ../..
      dockerfile: ./clients/Dockerfile
    volumes:
      - ../../clients:/app/clients
    command: npm run dev 
    
  services-api:
    volumes:
      - ../../dbs/main/data:/app/dbs/main/data
    build:
      context: ../..
      dockerfile: services/api/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
    develop:
      watch:
        - action: sync+restart
          path: ../../dbs/main
          target: /app/dbs/main
          ignore:
            - data
        - action: sync+restart
          path: ../../lib/node-express
          target: /app/lib/node-express
        - action: sync+restart
          path: ../../specs/apis/dist
          target: /app/specs/apis/dist
        - action: sync+restart
          path: ../../lib/drizzle-sqlite3
          target: /app/lib/drizzle-sqlite3
        - action: sync+restart
          path: .
          target: /app/services/api



  services-auth:
    volumes:
      - ../../dbs/auth/data:/app/dbs/auth/data
    build:
      context: ../..
      dockerfile: services/auth/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
    develop:
      watch:
        - action: sync+restart
          path: ../../dbs/auth
          target: /app/dbs/auth
          ignore:
            - data
        - action: sync+restart
          path: ../../lib/node-express
          target: /app/lib/node-express
        - action: sync+restart
          path: ../../specs/apis/dist
          target: /app/specs/apis/dist
        - action: sync+restart
          path: ../../lib/drizzle-sqlite3
          target: /app/lib/drizzle-sqlite3
        - action: sync+restart
          path: .
          target: /app/services/auth
    
  specs-apis:
    build:
      context: ../..
      dockerfile: ./specs/apis/Dockerfile
    volumes:
      - ./dist:/app/specs/apis/dist
    develop:
      watch:
        - action: sync+restart
          path: ./openapi.yaml
          target: /app/specs/apis/openapi.yaml
    command: npm run generate-and-serve 

volumes:
  caddy_data:
  caddy_config: 