services:
  api:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: api
    volumes: !override []
  auth:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: auth
    volumes: !override []
  caddy:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: caddy
    volumes: !override []
volumes:
  caddy_data:
  caddy_config:
