services:
  caddy:
    environment:
      - DISABLE_CADDY_PROD_SERVER=#

  clients:
    volumes:
      - ../../clients/spas:/app/clients/spas
      - ../../saflib/:/app/saflib/
    command: npm run dev

  docs:
    volumes:
      - ../../clients/docs:/app/clients/docs
      - ../../saflib/:/app/saflib/
    command: npm run docs:dev -- --host
