# common elements between dev and test
services:
  caddy:
    image: caddy:2.9.1
    ports:
      - 80:80
    volumes:
      - ./remote-assets/config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - PROTOCOL=${PROTOCOL}
    depends_on:
      - clients

  clients:
    # Named for local dev, but doesn't get published; not needed for prod
    image: saf-2025-clients:latest
    build:
      context: ../..
      dockerfile: ./clients/spas/Dockerfile

  api:
    image: ghcr.io/sderickson/saf-2025-api:latest
    volumes:
      - ../../dbs/main/data:/app/dbs/main/data
    build:
      context: ../..
      dockerfile: services/api/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}

  auth:
    image: ghcr.io/sderickson/saf-2025-auth:latest
    volumes:
      - ../../saflib/auth-db/data:/app/saflib/auth-db/data
      - ../../saflib/auth-service/data:/app/saflib/auth-service/data
    build:
      context: ../..
      dockerfile: saflib/auth-service/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - ALLOW_ADMIN_SIGNUPS=true
  specs-apis:
    build:
      context: ../..
      dockerfile: ./specs/apis/Dockerfile
    volumes:
      - ../../specs/apis/dist:/app/specs/apis/dist
    command: npm run generate-and-serve

volumes:
  caddy_data:
  caddy_config:
