# common elements between dev, test and prod
services:
  caddy:
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - PROTOCOL=${PROTOCOL}
    build:
      context: .
      dockerfile: Dockerfile.prod
  services-api:
    volumes:
      - ../../dbs/main/data:/app/dbs/main/data
    build:
      context: ../..
      dockerfile: services/api/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}

  services-auth:
    volumes:
      - ../../dbs/auth/data:/app/dbs/auth/data
    build:
      context: ../..
      dockerfile: services/auth/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
    
  specs-apis:
    build:
      context: ../..
      dockerfile: ./specs/apis/Dockerfile
    volumes:
      - ../../specs/apis/dist:/app/specs/apis/dist
    command: npm run generate-and-serve 

volumes:
  caddy_data:
  caddy_config: 