services:
  api:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: api
    volumes: !override []
  auth:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: auth
    volumes: !override []
    environment:
      # playwright depends on these.
      # TODO: Set this somehow in the e2e folder
      - ADMIN_EMAILS=admin-firefox@example.com,admin-chromium@example.com
      - DISABLE_RATE_LIMITING=true
      - SMTP_HOST=smtp.mock.com
  caddy:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: caddy
    volumes: !override []
volumes:
  caddy_data:
  caddy_config:
