# syntax=docker/dockerfile:labs
FROM oven/bun:latest

RUN ls

# install saflib
WORKDIR /app
COPY tsconfig.json ./

# copy packages
#{ copy_packages }#
COPY ./bun.lockb ./bun.lockb

RUN bun install --filter ./services/api --production

# Copy source files
#{ copy_src }#

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD ["bun", "run", "healthcheck"]
WORKDIR /app/services/api
CMD ["bun", "run", "start"]