services:
  services-api:
    volumes:
      - ../../dbs/main/data:/app/dbs/main/data
    build:
      context: ../..
      dockerfile: services/api/Dockerfile
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync+restart
          path: ../../dbs/main
          target: /app/dbs/main
          ignore:
            - data
        - action: sync+restart
          path: ../../lib/node-express
          target: /app/lib/node-express
        - action: sync+restart
          path: ../../specs/apis/dist
          target: /app/specs/apis/dist
        - action: sync+restart
          path: ../../lib/drizzle-sqlite3
          target: /app/lib/drizzle-sqlite3
        - action: sync+restart
          path: .
          target: /app/services/api
