# syntax=docker/dockerfile:labs
FROM node:22-slim

# install saflib
WORKDIR /app
COPY tsconfig.json ./

# copy packages
#{ copy_packages }#

RUN npm install --omit=dev

# Copy source files
#{ copy_src }#

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD ["npm", "run", "healthcheck"]
WORKDIR /app/services/api
CMD ["npm", "start"]