# openapi.yaml
openapi: 3.0.0
info:
  title: Your Product's API
  version: "1.0.0"
  description: The API used internally by web clients.
servers:
  - url: http://api.docker.localhost/
    description: Development server

components:
  securitySchemes:
    scopes:
      type: apiKey
      in: header
      name: X-User-Scopes
      description: Comma-separated list of user scopes
  schemas:
    Todo:
      $ref: "./schemas/todo.yaml"

paths:
  /todos:
    get:
      $ref: "./routes/todos.yaml#/get"
    post:
      $ref: "./routes/todos.yaml#/post"
    delete:
      $ref: "./routes/todos.yaml#/delete"
  /todos/{id}:
    put:
      $ref: "./routes/todos.yaml#/~1{id}/put"
    delete:
      $ref: "./routes/todos.yaml#/~1{id}/delete"
