# openapi.yaml
openapi: 3.0.0
info:
  title: Your Product's API
  version: "1.0.0"
  description: The API used internally by web clients.
servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /auth/register:
    post:
      $ref: "./routes/auth.yaml#/register/post"
  /auth/login:
    post:
      $ref: "./routes/auth.yaml#/login/post"
  /auth/logout:
    post:
      $ref: "./routes/auth.yaml#/logout/post"
  /auth/verify:
    get:
      $ref: "./routes/auth.yaml#/verify/get"
  /todos:
    get:
      $ref: "./routes/todos.yaml#/get"
    post:
      $ref: "./routes/todos.yaml#/post"
  /todos/{id}:
    put:
      $ref: "./routes/todos.yaml#/~1{id}/put"
    delete:
      $ref: "./routes/todos.yaml#/~1{id}/delete"
  /examples:
    get:
      $ref: "./routes/example.yaml#/get"
    post:
      $ref: "./routes/example.yaml#/post"
  /examples/{id}:
    get:
      $ref: "./routes/example.yaml#/~1{id}/get"

components:
  schemas:
    User:
      $ref: "./schemas/user.yaml"
    Todo:
      $ref: "./schemas/todo.yaml"
