# openapi.yaml
openapi: 3.0.0
info:
  title: Your Product's API
  version: "1.0.0"
  description: The API used internally by web clients.
servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /auth/login:
    post:
      $ref: "./routes/auth.yaml#/login/post"
  /auth/logout:
    post:
      $ref: "./routes/auth.yaml#/logout/post"
  /auth/verify:
    post:
      $ref: "./routes/auth.yaml#/verify/post"
  /users:
    get:
      $ref: "./routes/users.yaml#/get"
    post:
      $ref: "./routes/users.yaml#/post"
  /todos:
    get:
      $ref: "./routes/todos.yaml#/get"
    post:
      $ref: "./routes/todos.yaml#/post"
  /todos/{id}:
    put:
      $ref: "./routes/todos.yaml#/~1{id}/put"
    delete:
      $ref: "./routes/todos.yaml#/~1{id}/delete"

components:
  schemas:
    User:
      $ref: "./schemas/user.yaml"
    Todo:
      $ref: "./schemas/todo.yaml"
