# openapi.yaml
openapi: 3.0.0
info:
  title: Your Product's API
  version: "1.0.0"
  description: The API used internally by web clients.
servers:
  - url: http://api.docker.localhost/
    description: Development server

paths:
  /todos:
    get:
      $ref: "./routes/todos.yaml#/get"
    post:
      $ref: "./routes/todos.yaml#/post"
  /todos/{id}:
    put:
      $ref: "./routes/todos.yaml#/~1{id}/put"
    delete:
      $ref: "./routes/todos.yaml#/~1{id}/delete"

components:
  schemas:
    Todo:
      $ref: "./schemas/todo.yaml"
