# openapi.yaml
openapi: 3.0.0
info:
  title: Your Product's API
  version: "1.0.0"
  description: The API used internally by web clients.
servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /auth/login:
    post:
      $ref: "./routes/auth.yaml#/login/post"
  /auth/logout:
    post:
      $ref: "./routes/auth.yaml#/logout/post"
  /users:
    get:
      $ref: "./routes/users.yaml#/get"
    post:
      $ref: "./routes/users.yaml#/post"

components:
  schemas:
    User:
      $ref: "./schemas/user.yaml"
